### ISSUE TITLE
commit 54def43854675971ffc402ef91f24280f6bf4879 breaks with golang 1.6

### ISSUE THREAD

**Issue by nuclearcat** [collectd/go-collectd#24] opened 2016-08-29 19:32 UTC
../collectd.org/api/main.go:5:2: cannot find package "context" in any of:
        /root/go/src/vendor/context (vendor tree)
        /usr/lib/go/src/context (from $GOROOT)
        /root/go/src/context (from $GOPATH)

Maybe problem similar to this one
https://groups.google.com/forum/#!topic/golang-nuts/kpmMRtqvCiQ

**Comment by octo** [comment] 2016-08-30 20:49
Hi @nuclearcat,

that is correct and expected. Unfortunately, I'm not aware of a technique that would allow us to use `x/net/context` when compiling with Go 1.6 and `context` when compiling with 1.7. Do you have a suggestion?

Best regards,
—octo

**Comment by octo** [comment] 2016-09-05 06:51
Won't fix: working as intended.

Everything up to (and including) the `v0.2.0` tag is compatible with Go 1.6.

**Closed by octo** 2016-09-05 06:51 UTC
